### ISSUE TITLE
CI: mypy tests failing 

### ISSUE THREAD

**Issue by fchorney** [invenia/GitLabChangelog#17]
https://github.com/invenia/GitLabChangelog/runs/4876840823?check_suite_focus=true

```
check run-test: commands[3] | mypy gitlabchangelog
gitlabchangelog/changelog.py:93: error: Incompatible return value type (got "Optional[RESTObject]", expected "Optional[ProjectTag]")
gitlabchangelog/changelog.py:115: error: Incompatible return value type (got "List[RESTObject]", expected "List[ProjectIssue]")
gitlabchangelog/changelog.py:138: error: Incompatible return value type (got "List[RESTObject]", expected "List[ProjectMergeRequest]")
gitlabchangelog/changelog.py:203: error: Value of type "Union[RESTObjectList, List[RESTObject]]" is not indexable
```

**Comment by arnaudh** [comment]
These type changes are due to python-gitlab 3.0.0:
- The [last successful CI job](https://github.com/invenia/GitLabChangelog/runs/4709940696?check_suite_focus=true) was using python-gitlab 2.10.1
- The [next day](https://github.com/invenia/GitLabChangelog/runs/4722715353?check_suite_focus=true) the tests started failing with python-gitlab 3.0.0 

[python-gitlab 3.0.0 introduces a few breaking changes](https://python-gitlab.readthedocs.io/en/stable/changelog.html#v3-0-0-2022-01-05), and because we mock python-gitlab in the tests, I'm not confident making changes to support it right now.

I'll limit python-gitlab to < 3.0.0 and create an issue to support 3.0.0.

**Comment by arnaudh** [comment]
Fixed with https://github.com/invenia/GitLabChangelog/pull/18
